---
project:
  description: Module::ScanDeps::Static
  author:
    name: Rob Lauer
    mailto: rclauer@gmail.com
pm_module: Module::ScanDeps::Static
min-perl-version: 5.010
dependencies:
  requires: requires
  test_requires: test-requires
path:
  pm_module: lib
  exe_files: bin
  tests: t
extra-files:
  - ChangeLog
  - share:
      - README.md
resources:
  bugtracker:
    mailto: rclauer@gmail.com
    web: https://github.com/rlauer6/Module-ScanDeps-Static/issues
  homepage: https://github.com/rlauer6/Module-ScanDeps-Static
  repository:
    type: git
    url: git@github.com:rlauer6/Module-ScanDeps-Static.git
    web: https://github.com/rlauer6/Module-ScanDeps-Static
